export const routes = {
    signin: "/signin",
    signup: "/signup",
    home: "/",
    profile: "/profile",
    organizerRegistration: "/organizer-registration",
    organizerRegistrationDetail: "/organizer-registration/:id",
    eventManagement: "/event",
    eventDetail: "/event/:id",
    category: "/category",
    setting: "/setting",
    resalePost: "/resale-post",
    resalePostDetail: "/resale-post/:id",
    tag: "/tag",
    user: "/user",
    userDetail: "/user/:id",
    confirmUser: "/confirm-user",
    changePassWord: "/change-password",
    stats: "/stats",
    overview: "/overview",
    withdrawalRequest: "/withdrawal-request",
    withdrawalRequestDetail: "/withdrawal-request/:id",
}